package sansastone;

import javax.swing.*;
import java.awt.*;
/**
 * Created by Cristian Navarrete on 27-09-16.
 */
public class ModoJuegoView extends JFrame {

    private JButton a1JugadorButton;
    private JButton a2JugadoresButton;
    private JPanel Portada;

/******** Funcion: ModoJuegoView ********************
Descripcion: Constructor que establece la ventana de
seleccion de modo
Parametros:
Sansano s1
Sansano s2
************************************************/
    public ModoJuegoView(Sansano s1, Sansano s2) {
        setContentPane(Portada);
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        a1JugadorButton.addActionListener(e -> {
            ModoJuego juego = new UnJugador();
            juego.iniciar(ModoJuegoView.this, s1, s2);
            juego.DesarrolloJuego();
        });
        a2JugadoresButton.addActionListener(e -> {
            ModoJuego juego = new ConUnAmigo();
            juego.iniciar(ModoJuegoView.this, s1, s2);
            juego.DesarrolloJuego();

        });
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */

    /******** Funcion: activar ********************
Descripcion: metodo para el funcionamiento fuera de intellij ide
Parametros:
None
Retorno: void
************************************************/
    private void $$$setupUI$$$() {
        Portada = new JPanel();
        Portada.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(20, 20, 20, 20), -1, -1));
        a1JugadorButton = new JButton();
        a1JugadorButton.setText("1 Jugador");
        Portada.add(a1JugadorButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        Portada.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(362, 11), null, 0, false));
        a2JugadoresButton = new JButton();
        a2JugadoresButton.setText("2 Jugadores");
        Portada.add(a2JugadoresButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        Portada.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Bienvenido a SansaStone");
        Portada.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(400, -1), null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Portada;
    }
}
